### ISSUE TITLE
Motor file parsing

### ISSUE THREAD

**Issue by jb803** [cuspaceflight/m3cfd#14]
The rough design team will specify a commercial motor to use for the simulation. We need to know the mass of the motor, its centre of gravity and the force produced at a given time after ignition. This is all found in the .rse files available on http://www.thrustcurve.org/ (e.g. http://www.thrustcurve.org/simfilesearch.jsp?id=1800 ). 

Unfortunately the format is a bit nasty so it would be great if someone could write something to parse a .rse file and spit out a csv file of the form: 'time,thrust,mass,cg'

**Comment by rjw57** [comment]
I added a comment on #15 about a way this might be added to the ``cusfsim`` package.

**Comment by rjw57** [comment]
@JMW95 and I are going to meet up to try and pair-program the :hankey: out of this.
